export type { Database, Json } from './database.types';

export const TABLES = {
  hotels: 'hotels',
  hotelUsers: 'hotel_users',
  superAdmins: 'super_admins',
  faqs: 'faqs',
  amenities: 'amenities',
  hours: 'hours',
  policies: 'policies',
  eventsInternal: 'events_internal',
  rooms: 'rooms',
  guestSessions: 'guest_sessions',
  messages: 'messages',
  businessCategories: 'business_categories',
  businesses: 'businesses',
  businessOfferings: 'business_offerings',
  partnerships: 'partnerships',
  referrals: 'referrals',
  bookings: 'bookings',
  commissionEvents: 'commission_events',
  recommendationRules: 'recommendation_rules',
  intents: 'intents',
  featureFlags: 'feature_flags',
  auditLog: 'audit_log',
  stripeWebhookEvents: 'stripe_webhook_events',
  knowledgeChunks: 'knowledge_chunks',
  rateLimitEvents: 'rate_limit_events',
  profiles: 'profiles',
  partnerApplications: 'partner_applications',
  businessOwners: 'business_owners',
  userFavorites: 'user_favorites',
  userVisits: 'user_visits',
  userRecentViews: 'user_recent_views',
} as const;

export type TableName = (typeof TABLES)[keyof typeof TABLES];
